# Generated by Django 5.1.4 on 2024-12-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('news_url', models.URLField(null=True, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
