# Generated by Django 5.1.4 on 2025-01-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_userpreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
