# Generated by Django 5.1.4 on 2025-01-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0005_alter_news_author_alter_news_content_alter_news_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_updating', models.BooleanField(default=False)),
            ],
        ),
    ]
