# Generated by Django 5.1.4 on 2025-01-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0006_newsupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsupdate',
            name='is_updating',
        ),
    ]
